### ISSUE TITLE
Implement a signup screen for all User Types

### ISSUE THREAD

**Issue by jules2689** [CodeForKids/cfk_finder#6]
## What we need
- We need a signup field that accurately represents and easily allows subscription for Tutors, Customers, and Admins
- This should include a general information screen, and a screen for specific information (i.e. kids info for customers).

We should investigate a simple signup and try to infer as much data as possible.
## Tasks
- [x] Design general screen
- [x] Design screen for tutors
- [x] Design screen for customers
- [ ] Design screen for admins
- [x] Implement screens in HTML and ERB
- [x] Some generic mechanism that shows the relevant screens based on the type of user
